# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_spatial_sign <- function(x, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_sign`, x, zero_tol)
}

cpp_spatial_median <- function(x, weights, initial, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_median`, x, weights, initial, tol, max_iter, zero_tol)
}

cpp_spatial_rank <- function(x, reference, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_rank`, x, reference, zero_tol)
}

cpp_spatial_kendall <- function(x, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_kendall`, x, zero_tol)
}

cpp_tyler_shape <- function(centered, initial, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_tyler_shape`, centered, initial, tol, max_iter, zero_tol)
}

cpp_acg_loglik <- function(x, shape) {
    .Call(`_HDElliptical_cpp_acg_loglik`, x, shape)
}

cpp_hr_estimator <- function(x, initial_location, initial_shape, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_hr_estimator`, x, initial_location, initial_shape, tol, max_iter, zero_tol)
}

#' One-sample Zhang--Feng marginal signed-rank scores
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @return Internal list of marginal scores and exact untied null moments.
#' @keywords internal
cpp_zhang_feng_one_sample_scores <- function(x, mu) {
    .Call(`_HDElliptical_cpp_zhang_feng_one_sample_scores`, x, mu)
}

#' Two-sample Zhang--Feng marginal WMW scores
#'
#' @param x First numeric observation-by-variable matrix.
#' @param y Second numeric observation-by-variable matrix.
#' @return Internal list of marginal scores and exact untied null moments.
#' @keywords internal
cpp_zhang_feng_two_sample_scores <- function(x, y) {
    .Call(`_HDElliptical_cpp_zhang_feng_two_sample_scores`, x, y)
}

#' Ouyang Parzen long-run variance estimate for rank-square scores
#'
#' @param score Numeric standardized squared-rank score sequence.
#' @param lag Explicit lag-window size L; lags 1 through L - 1 are used.
#' @return Internal list of sample autocovariances, weights, and tau squared.
#' @keywords internal
cpp_zhang_feng_parzen_tau <- function(score, lag) {
    .Call(`_HDElliptical_cpp_zhang_feng_parzen_tau`, score, lag)
}

#' Construct standardised contrasts for the analytical aSPU test
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param correlation_source One of `"common"`, `"unequal"`, or
#'   `"supplied"`.
#' @param bandwidth1,bandwidth2 Hard-band widths; `-1` means no banding.
#' @param supplied_correlation Optional supplied correlation matrix.
#' @param supplied_standard_errors Optional supplied marginal standard errors.
#' @return Internal list of contrasts and covariance diagnostics.
#' @keywords internal
cpp_aspu_standardize <- function(x, y, correlation_source, bandwidth1, bandwidth2, supplied_correlation, supplied_standard_errors) {
    .Call(`_HDElliptical_cpp_aspu_standardize`, x, y, correlation_source, bandwidth1, bandwidth2, supplied_correlation, supplied_standard_errors)
}

#' Gaussian finite-power moments for the analytical aSPU test
#'
#' @param scores Finite-power coordinate scores.
#' @param covariance Their null covariance matrix.
#' @param powers Positive finite integer powers.
#' @return Internal list of observed sums and Gaussian moment matrices.
#' @keywords internal
cpp_aspu_power_moments <- function(scores, covariance, powers) {
    .Call(`_HDElliptical_cpp_aspu_power_moments`, scores, covariance, powers)
}

#' Adaptive-threshold precision estimator for the feasible CLX test
#'
#' The pooled covariance and the variance estimates used in its entrywise
#' thresholds both have denominator N = n1 + n2.  The threshold is
#' delta * sqrt(theta_ij * log(p) / N).  A relative eigenvalue floor is
#' applied only when needed to invert the thresholded covariance matrix.
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param delta Positive adaptive-threshold multiplier.
#' @param relative_eigen_floor Non-negative relative eigenvalue floor.
#' @return Internal list containing the precision estimate and diagnostics.
#' @keywords internal
cpp_clx_adaptive_precision <- function(x, y, delta, relative_eigen_floor) {
    .Call(`_HDElliptical_cpp_clx_adaptive_precision`, x, y, delta, relative_eigen_floor)
}

#' Oracle or feasible Cai--Liu--Xia statistic kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param precision Symmetric precision or estimated-precision matrix.
#' @param oracle If true, use diag(precision); otherwise use equation (7).
#' @return Internal list of statistic components.
#' @keywords internal
cpp_clx_two_sample <- function(x, y, precision, oracle) {
    .Call(`_HDElliptical_cpp_clx_two_sample`, x, y, precision, oracle)
}

#' Feng--Zou--Wang--Zhu Composite T-squared two-sample kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param block_size Positive block size no larger than the dimension.
#' @param selection Block construction rule. Currently `"paper_greedy"`.
#' @return Internal list of statistic, trace, and partition diagnostics.
#' @keywords internal
cpp_composite_t2_two_sample <- function(x, y, block_size = 2L, selection = "paper_greedy") {
    .Call(`_HDElliptical_cpp_composite_t2_two_sample`, x, y, block_size, selection)
}

cpp_erht_grid <- function(residuals_scaled, null_difference_scaled, rho, keep_companion = FALSE) {
    .Call(`_HDElliptical_cpp_erht_grid`, residuals_scaled, null_difference_scaled, rho, keep_companion)
}

#' Feng--Sun one-sample spatial-sign statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @param tolerance Positive equation-residual tolerance.
#' @param max_iterations Positive maximum update count.
#' @return Internal list of feasible statistic components and leave-out fits.
#' @keywords internal
cpp_feng_sun_one_sample <- function(x, mu, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_feng_sun_one_sample`, x, mu, tolerance, max_iterations)
}

#' Feng--Zou--Wang two-sample multivariate-sign kernel
#'
#' @param x First numeric observation-by-variable matrix.
#' @param y Second numeric observation-by-variable matrix.
#' @param tolerance Positive estimating-equation tolerance.
#' @param max_iterations Positive maximum update count per fit.
#' @return Internal list containing the feasible statistic and diagnostics.
#' @keywords internal
cpp_feng_zou_wang_two_sample_sign <- function(x, y, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_feng_zou_wang_two_sample_sign`, x, y, tolerance, max_iterations)
}

#' Feng--Zou--Wang--Zhu Behrens--Fisher statistic kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_fzwz_bf_two_sample <- function(x, y) {
    .Call(`_HDElliptical_cpp_fzwz_bf_two_sample`, x, y)
}

#' Strict initial values for the generic weighted HR recursion
#'
#' @param x Observation-by-coordinate finite numeric matrix.
#' @return Column means and unbiased marginal variances.
#' @keywords internal
cpp_ch2_generic_weighted_initial <- function(x) {
    .Call(`_HDElliptical_cpp_ch2_generic_weighted_initial`, x)
}

#' Spatial geometry and unweighted diagonal HR update
#'
#' @param x Observation-by-coordinate finite numeric matrix.
#' @param location Current location vector.
#' @param diagonal Current strictly positive diagonal scale.
#' @param zero_tol Non-negative singular-radius threshold.
#' @return Directions, radii, and the literal unweighted HR scale update.
#' @keywords internal
cpp_ch2_generic_weighted_geometry <- function(x, location, diagonal, zero_tol) {
    .Call(`_HDElliptical_cpp_ch2_generic_weighted_geometry`, x, location, diagonal, zero_tol)
}

#' Literal generic weighted HR location update
#'
#' @param location Current location vector.
#' @param diagonal Current strictly positive diagonal scale.
#' @param directions Current spatial directions.
#' @param radii Current strictly positive radii.
#' @param weights Evaluated finite radial weights.
#' @return The weighted numerator, denominator, and next location.
#' @keywords internal
cpp_ch2_generic_weighted_step <- function(location, diagonal, directions, radii, weights) {
    .Call(`_HDElliptical_cpp_ch2_generic_weighted_step`, location, diagonal, directions, radii, weights)
}

#' Generic oracle weighted-sign quadratic U-statistic
#'
#' @param directions Observation-by-coordinate unit spatial directions.
#' @param weights Evaluated finite radial weights.
#' @return The literal pairwise score and empirical weight moment.
#' @keywords internal
cpp_ch2_generic_weighted_quadratic <- function(directions, weights) {
    .Call(`_HDElliptical_cpp_ch2_generic_weighted_quadratic`, directions, weights)
}

cpp_feng_zhang_liu_spatial_rank <- function(x, y, tolerance, max_iterations, scale_identification) {
    .Call(`_HDElliptical_cpp_feng_zhang_liu_spatial_rank`, x, y, tolerance, max_iterations, scale_identification)
}

#' Feng--Liu--Ma one-sample inverse norm sign statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @param tol Positive relative-update tolerance.
#' @param max_iter Positive maximum number of updates per leave-two-out fit.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal list of primary statistic, direct feasible variance,
#'   cross-fitted nuisance diagnostics, and iteration diagnostics.
#' @keywords internal
cpp_inst_one_sample <- function(x, mu, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_inst_one_sample`, x, mu, tol, max_iter, zero_tol)
}

#' Park--Ayyala one-sample statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-mean vector.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_park_ayyala_one_sample <- function(x, mu) {
    .Call(`_HDElliptical_cpp_park_ayyala_one_sample`, x, mu)
}

#' Chen--Qin two-sample statistic kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_chen_qin_two_sample <- function(x, y) {
    .Call(`_HDElliptical_cpp_chen_qin_two_sample`, x, y)
}

cpp_hotelling_one_sample <- function(x, mu, tol) {
    .Call(`_HDElliptical_cpp_hotelling_one_sample`, x, mu, tol)
}

cpp_hotelling_two_sample <- function(x, y, tol) {
    .Call(`_HDElliptical_cpp_hotelling_two_sample`, x, y, tol)
}

cpp_spatial_sign_test <- function(x, mu, tol, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_sign_test`, x, mu, tol, zero_tol)
}

cpp_spatial_signed_rank_test <- function(x, mu, tol, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_signed_rank_test`, x, mu, tol, zero_tol)
}

cpp_spatial_rank_test <- function(x, y, tol, zero_tol) {
    .Call(`_HDElliptical_cpp_spatial_rank_test`, x, y, tol, zero_tol)
}

#' Li--Wang--Zou simpler spatial-sign two-sample kernel
#'
#' @param x First numeric observation-by-variable matrix.
#' @param y Second numeric observation-by-variable matrix.
#' @param tol Positive estimating-equation tolerance.
#' @param max_iter Positive maximum update count for each full-sample fit.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal list containing the feasible SST and diagnostics.
#' @keywords internal
cpp_li_wang_zou_two_sample_sign <- function(x, y, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_li_wang_zou_two_sample_sign`, x, y, tol, max_iter, zero_tol)
}

#' Zhang--Zhou--Guo one-sample normal-reference kernel
#'
#' @param residual Numeric matrix of null-centred observations.  A common
#'   positive scaling of this matrix leaves the reported calibration
#'   unchanged.
#'
#' @return Internal list of the centred U-statistic, unbiased trace
#'   estimates, cumulants, and shifted-scaled chi-square parameters.
#'
#' @keywords internal
cpp_zhang_zhou_guo_one_sample <- function(residual) {
    .Call(`_HDElliptical_cpp_zhang_zhou_guo_one_sample`, residual)
}

cpp_zhang_zhu_zhang_two_sample <- function(x, y) {
    .Call(`_HDElliptical_cpp_zhang_zhu_zhang_two_sample`, x, y)
}

#' Feng--Wang PDQ spatial-sign kernel
#'
#' @param x,y Numeric matrices with observations in rows.
#' @param quantile_prob Pairwise-difference U-quantile probability.
#' @param level Test level used for the primary empirical critical value.
#' @param B Number of Rademacher draws.
#' @param seed Integer-valued counter-generator seed represented as a double.
#' @param keep_bootstrap Whether to retain bootstrap values and multipliers.
#' @param tolerance Spatial-median estimating-equation tolerance.
#' @param max_iterations Maximum spatial-median iterations.
#' @return A list of the statistic, nuisance fits, bootstrap calibration, and
#'   numerical diagnostics.
#' @keywords internal
cpp_feng_wang_pdq_two_sample <- function(x, y, quantile_prob, level, B, seed, keep_bootstrap, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_feng_wang_pdq_two_sample`, x, y, quantile_prob, level, B, seed, keep_bootstrap, tolerance, max_iterations)
}

#' Srivastava--Du one-sample statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-mean vector.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_srivastava_du_one_sample <- function(x, mu) {
    .Call(`_HDElliptical_cpp_srivastava_du_one_sample`, x, mu)
}

#' Original Bai--Saranadasa two-sample statistic kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_bai_saranadasa_two_sample <- function(x, y) {
    .Call(`_HDElliptical_cpp_bai_saranadasa_two_sample`, x, y)
}

#' Srivastava--Katayama--Kano statistic kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @return Internal list of statistic components.
#' @keywords internal
cpp_skk_two_sample <- function(x, y) {
    .Call(`_HDElliptical_cpp_skk_two_sample`, x, y)
}

#' Full-sample scaled spatial median kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param target Finite centering vector. Ignored when `center_on_target` is
#'   false.
#' @param center_on_target Whether to express the fit relative to `target`.
#' @param tol Positive estimating-equation tolerance.
#' @param max_iter Positive maximum update count.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal fit, max statistic ingredients, and diagnostics.
#' @keywords internal
cpp_scaled_spatial_median <- function(x, target, center_on_target, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_scaled_spatial_median`, x, target, center_on_target, tol, max_iter, zero_tol)
}

cpp_zhao_feng_strongcorr_sign_bootstrap <- function(x, mu, fitted_location, multiplier, B, alpha, keep_bootstrap) {
    .Call(`_HDElliptical_cpp_zhao_feng_strongcorr_sign_bootstrap`, x, mu, fitted_location, multiplier, B, alpha, keep_bootstrap)
}

#' Huang--Liu--Zhou--Feng two-sample inverse norm sign kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param tol Positive estimating-equation tolerance.
#' @param max_iter Positive maximum number of updates for every fit.
#' @param zero_tol Non-negative standardized zero-residual tolerance.
#' @return Internal list of tINST statistic and convergence components.
#' @keywords internal
cpp_tinst_two_sample <- function(x, y, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_tinst_two_sample`, x, y, tol, max_iter, zero_tol)
}

#' Wang--Xu approximate-randomization kernel
#'
#' @param x,y Numeric observation-by-variable matrices.
#' @param calibration Either `"exact"` or `"monte_carlo"`; `"auto"` is
#'   resolved by the public R wrapper.
#' @param B Positive Monte Carlo draw count (ignored for exact enumeration).
#' @param seed Integer-valued counter-generator seed represented as a double.
#' @param max_exact Maximum number of global-sign-reduced exact patterns.
#' @param keep_randomized Whether to retain statistics and sign patterns.
#' @return Internal observed, pseudo-sample, reference, and diagnostic fields.
#' @keywords internal
cpp_wang_xu_approx_randomization <- function(x, y, calibration, B, seed, max_exact, keep_randomized) {
    .Call(`_HDElliptical_cpp_wang_xu_approx_randomization`, x, y, calibration, B, seed, max_exact, keep_randomized)
}

#' Weighted scaled spatial median and diagonal scale kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param m Finite radial power no greater than one.
#' @param tol Positive relative-update tolerance.
#' @param max_iter Positive maximum number of updates.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal list containing the fitted location, diagonal scale,
#'   radial quantities, and iteration diagnostics.
#' @keywords internal
cpp_weighted_scaled_spatial_median <- function(x, m, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_weighted_scaled_spatial_median`, x, m, tol, max_iter, zero_tol)
}

#' Yan--Zhao--Feng weighted max statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @param m Finite radial power no greater than one.
#' @param tol Positive relative-update tolerance.
#' @param max_iter Positive maximum number of updates.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal list containing the weighted max statistic and fit.
#' @keywords internal
cpp_yzf_weighted_max <- function(x, mu, m, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_yzf_weighted_max`, x, mu, m, tol, max_iter, zero_tol)
}

#' Yan--Zhao--Feng weighted max-sum statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @param m Finite radial power no greater than one.
#' @param tol Positive relative-update tolerance.
#' @param max_iter Positive maximum number of updates.
#' @param zero_tol Non-negative singular-radius tolerance.
#' @return Internal list containing weighted max and feasible weighted sum
#'   components and all fit diagnostics.
#' @keywords internal
cpp_yzf_weighted_maxsum <- function(x, mu, m, tol, max_iter, zero_tol) {
    .Call(`_HDElliptical_cpp_yzf_weighted_maxsum`, x, mu, m, tol, max_iter, zero_tol)
}

#' Wang--Peng--Li one-sample spatial-sign statistic kernel
#'
#' @param x Numeric observation-by-variable matrix.
#' @param mu Numeric null-location vector.
#' @return Internal list of statistic and cross-validation components.
#' @keywords internal
cpp_wang_peng_li_one_sample <- function(x, mu) {
    .Call(`_HDElliptical_cpp_wang_peng_li_one_sample`, x, mu)
}

cpp_ch3ef_tyler_one_step <- function(x, center, precision, zero_tolerance) {
    .Call(`_HDElliptical_cpp_ch3ef_tyler_one_step`, x, center, precision, zero_tolerance)
}

cpp_elliptical_sphericity_sign_core <- function(residuals, center_scaled, compute_second_order, keep_sscm) {
    .Call(`_HDElliptical_cpp_elliptical_sphericity_sign_core`, residuals, center_scaled, compute_second_order, keep_sscm)
}

cpp_elliptical_sphericity_rank_core <- function(x, method, keep_pair_signs) {
    .Call(`_HDElliptical_cpp_elliptical_sphericity_rank_core`, x, method, keep_pair_signs)
}

cpp_ch3_gaussian_sign_geometry <- function(residual) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_sign_geometry`, residual)
}

cpp_ch3_gaussian_rank_shape <- function(directions, scores, score_second_moment) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_rank_shape`, directions, scores, score_second_moment)
}

cpp_ch3_gaussian_threshold_matrix <- function(covariance, threshold, rule, shape, threshold_diagonal) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_threshold_matrix`, covariance, threshold, rule, shape, threshold_diagonal)
}

cpp_ch3_gaussian_product_variability <- function(residual, covariance) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_product_variability`, residual, covariance)
}

cpp_ch3_gaussian_trace_u_statistics <- function(x) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_trace_u_statistics`, x)
}

cpp_ch3_gaussian_li_chen <- function(x, y) {
    .Call(`_HDElliptical_cpp_ch3_gaussian_li_chen`, x, y)
}

cpp_ch3gp_ec2_l1 <- function(correlation, lambda, tau, rho, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ch3gp_ec2_l1`, correlation, lambda, tau, rho, tolerance, max_iterations)
}

cpp_ch3gp_offdiag_glasso <- function(scatter, lambda, tolerance, max_iterations, initial_step, max_backtracking) {
    .Call(`_HDElliptical_cpp_ch3gp_offdiag_glasso`, scatter, lambda, tolerance, max_iterations, initial_step, max_backtracking)
}

cpp_ch3gp_clime <- function(scatter, lambda, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ch3gp_clime`, scatter, lambda, tolerance, max_iterations)
}

cpp_ch3_hdhr_fit <- function(x, pilot_precision, bandwidth, median_tolerance, median_maximum_iterations, tolerance, maximum_iterations, zero_tolerance) {
    .Call(`_HDElliptical_cpp_ch3_hdhr_fit`, x, pilot_precision, bandwidth, median_tolerance, median_maximum_iterations, tolerance, maximum_iterations, zero_tolerance)
}

cpp_ollila_sample_moments <- function(x) {
    .Call(`_HDElliptical_cpp_ollila_sample_moments`, x)
}

cpp_ollila_sign_components <- function(residuals, keep_signs) {
    .Call(`_HDElliptical_cpp_ollila_sign_components`, residuals, keep_signs)
}

cpp_ollila_basic_inverse <- function(delta, dimension, quadrature_order, inversion_tolerance, integration_tolerance, max_iterations, max_bracket_iterations) {
    .Call(`_HDElliptical_cpp_ollila_basic_inverse`, delta, dimension, quadrature_order, inversion_tolerance, integration_tolerance, max_iterations, max_bracket_iterations)
}

cpp_ollila_pool_qp <- function(objective_matrix, linear_term, lower, convex, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ollila_pool_qp`, objective_matrix, linear_term, lower, convex, tolerance, max_iterations)
}

cpp_ch3pp_sscm_components <- function(signs_x, signs_y) {
    .Call(`_HDElliptical_cpp_ch3pp_sscm_components`, signs_x, signs_y)
}

cpp_ch3pp_spatial_rank_components <- function(x, y, zero_tolerance) {
    .Call(`_HDElliptical_cpp_ch3pp_spatial_rank_components`, x, y, zero_tolerance)
}

cpp_ch3pp_sclime <- function(a, lambda, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ch3pp_sclime`, a, lambda, tolerance, max_iterations)
}

cpp_ch3pp_sglasso <- function(a, lambda, tolerance, max_iterations, initial_step, max_backtracking) {
    .Call(`_HDElliptical_cpp_ch3pp_sglasso`, a, lambda, tolerance, max_iterations, initial_step, max_backtracking)
}

cpp_ch3teg_mode_crossproducts <- function(signs, dims) {
    .Call(`_HDElliptical_cpp_ch3teg_mode_crossproducts`, signs, dims)
}

cpp_ch3teg_whitened_mode_scatter <- function(signs, dims, pilot_sqrt, keep_vectors = FALSE) {
    .Call(`_HDElliptical_cpp_ch3teg_whitened_mode_scatter`, signs, dims, pilot_sqrt, keep_vectors)
}

cpp_ch3teg_offdiag_glasso <- function(scatter, penalty, tolerance, max_iterations, initial_step, max_backtracking) {
    .Call(`_HDElliptical_cpp_ch3teg_offdiag_glasso`, scatter, penalty, tolerance, max_iterations, initial_step, max_backtracking)
}

#' Core OLS quantities for unconditional factor-pricing alpha tests
#'
#' @param y Observation-by-asset numeric matrix, already column scaled.
#' @param factors Observation-by-factor numeric matrix, already column scaled.
#' @return A list of OLS quantities in the scaled coordinates.
#' @keywords internal
cpp_ch4_alpha_ols <- function(y, factors) {
    .Call(`_HDElliptical_cpp_ch4_alpha_ols`, y, factors)
}

#' Liu--Feng--Ma spatial-sign alpha core
#'
#' @param y Observation-by-asset numeric matrix, already column scaled.
#' @param factors Observation-by-factor numeric matrix, already column scaled.
#' @param tol Positive fixed-point tolerance.
#' @param max_iter Positive iteration limit.
#' @param zero_tol Non-negative standardized zero-radius tolerance.
#' @param compute_trace Whether to compute the primary split leave-two-out trace.
#' @return Components of the primary statistic.
#' @keywords internal
cpp_ch4_lfm_spatial_sign_core <- function(y, factors, tol, max_iter, zero_tol, compute_trace) {
    .Call(`_HDElliptical_cpp_ch4_lfm_spatial_sign_core`, y, factors, tol, max_iter, zero_tol, compute_trace)
}

#' Strict least-squares projection for conditional-alpha procedures
#'
#' @param y Finite observation-by-asset matrix on a common numerical scale.
#' @param design Finite full-column-rank observation-by-regressor matrix.
#' @return Restricted residuals, residualized intercept, coefficients, and
#'   exact numerical diagnostics.
#' @keywords internal
cpp_ch4_afc_project <- function(y, design) {
    .Call(`_HDElliptical_cpp_ch4_afc_project`, y, design)
}

#' Spatial Kendall matrix for robust latent-factor extraction
#'
#' @param x Finite observation-by-variable matrix.
#' @return Spatial Kendall matrix and the number of zero pair differences.
#' @keywords internal
cpp_ch4_afc_spatial_kendall <- function(x) {
    .Call(`_HDElliptical_cpp_ch4_afc_spatial_kendall`, x)
}

#' Light-tail conditional-alpha sum and maximum ingredients
#'
#' @param residuals Restricted residual matrix, observations by assets.
#' @param h Residualized intercept.
#' @param factor_count Number of observed factors in the primary marginal
#'   variance divisor.
#' @param design_columns Number of columns in the null sieve design.
#' @param compute_max Whether to require and compute maximum-test marginal
#'   variances.
#' @return Exact feasible sum, trace, variance, and maximum ingredients.
#' @keywords internal
cpp_ch4_afc_light_components <- function(residuals, h, factor_count, design_columns, compute_max) {
    .Call(`_HDElliptical_cpp_ch4_afc_light_components`, residuals, h, factor_count, design_columns, compute_max)
}

#' Robust conditional spatial-sign sum ingredients
#'
#' @param residuals Restricted residuals used in the CSS numerator.
#' @param trace_residuals Residuals from the primary uncentered-basis fit used
#'   in the off-diagonal trace estimator.
#' @param h Residualized intercept from the restricted null sieve design.
#' @return CSS numerator, trace estimator, signs, and diagnostics.
#' @keywords internal
cpp_ch4_afc_css_components <- function(residuals, trace_residuals, h) {
    .Call(`_HDElliptical_cpp_ch4_afc_css_components`, residuals, trace_residuals, h)
}

#' Coordinate CUSUMs and Rice difference variances
#'
#' Computes the literal gamma=0 and gamma=1/2 CUSUM arrays together with
#' `sum(diff(x)^2)/(2(n-1))`.  Columnwise anchors and long-double accumulators
#' reduce cancellation under a common translation.
#'
#' @param x Numeric observations in rows.
#' @return A list of two CUSUM matrices and the difference variance.
#' @keywords internal
ch4_cp_cusum_cpp <- function(x) {
    .Call(`_HDElliptical_ch4_cp_cusum_cpp`, x)
}

#' Wang--Feng finite-difference moment estimators
#'
#' Implements the displayed leave-four and leave-three estimators in the
#' primary paper.  The exclusion set is literally
#' `{2,...,n} \\ {i1,...,im}` and no bridging difference is inserted.
#'
#' @param x Numeric observations in rows.
#' @return Trace, radial fourth-moment, and term-level diagnostics.
#' @keywords internal
ch4_cp_dms_moments_cpp <- function(x) {
    .Call(`_HDElliptical_ch4_cp_dms_moments_cpp`, x)
}

#' Joint scaled spatial-median and diagonal fixed point
#'
#' Implements the three updates stated by Liu, Feng, Peng, and Wang.  The
#' common diagonal scale inherited from sample-variance initialization is
#' retained; only relative diagonal scale is identified.
#'
#' @param x Numeric observations in rows.
#' @param tol Relative-update tolerance.
#' @param max_iter Maximum iterations.
#' @param zero_tol Exact/near-zero residual tolerance; zero is the paper
#'   convention and positive values are user-requested diagnostics.
#' @return Fixed point and convergence diagnostics.
#' @keywords internal
ch4_cp_scaled_hr_cpp <- function(x, tol = 1e-8, max_iter = 1000L, zero_tol = 0.0) {
    .Call(`_HDElliptical_ch4_cp_scaled_hr_cpp`, x, tol, max_iter, zero_tol)
}

#' Spatial median with a coincident-point certificate
#'
#' Uses the modified Weiszfeld map.  At an iterate coinciding with observations,
#' the exact subgradient condition is checked rather than adding jitter.
#'
#' @param x Numeric observations in rows.
#' @param tol Relative-update tolerance.
#' @param max_iter Maximum iterations.
#' @param zero_tol Coincidence tolerance, with zero giving exact coincidence.
#' @return Median and convergence diagnostics.
#' @keywords internal
ch4_cp_spatial_median_cpp <- function(x, tol = 1e-8, max_iter = 1000L, zero_tol = 0.0) {
    .Call(`_HDElliptical_ch4_cp_spatial_median_cpp`, x, tol, max_iter, zero_tol)
}

#' Ordered-pair squared inner-product sum
#'
#' @param signs Matrix with observations in rows.
#' @return `sum_{i != j} (u_i' u_j)^2`.
#' @keywords internal
ch4_cp_ordered_pair_square_sum_cpp <- function(signs) {
    .Call(`_HDElliptical_ch4_cp_ordered_pair_square_sum_cpp`, signs)
}

#' ERHT companion center and variance
#'
#' Computes the ordered off-diagonal expression directly, avoiding
#' subtraction of two nearly equal non-negative matrix products.
#'
#' @param companion Symmetric companion matrix A.
#' @param beta Score-CUSUM weights.
#' @return Kappa, sigma squared, and the ordered off-diagonal sum.
#' @keywords internal
ch4_cp_erht_moments_cpp <- function(companion, beta) {
    .Call(`_HDElliptical_ch4_cp_erht_moments_cpp`, companion, beta)
}

#' Standardized residual radii for the Chapter 4 completion methods
#'
#' @param residuals Observation-by-coordinate residual matrix.
#' @param diagonal Strictly positive scale diagonal.
#' @return A vector of stable Euclidean radii.
#' @keywords internal
cpp_ch4_completion_standardized_radii <- function(residuals, diagonal) {
    .Call(`_HDElliptical_cpp_ch4_completion_standardized_radii`, residuals, diagonal)
}

#' Weighted spatial-sign alpha quadratic form
#'
#' @param directions Observation-by-asset spatial-sign matrix.
#' @param h Residualized-intercept vector.
#' @param weights Evaluated radial weights.
#' @return The quadratic form and empirical second weight moment.
#' @keywords internal
cpp_ch4_completion_weighted_alpha_q <- function(directions, h, weights) {
    .Call(`_HDElliptical_cpp_ch4_completion_weighted_alpha_q`, directions, h, weights)
}

#' Exact degenerate rank-U core for vector independence
#'
#' @param x Observation-by-coordinate first vector block.
#' @param y Observation-by-coordinate second vector block.
#' @param measure Zero for Hoeffding D, one for BKR R, two for tau-star.
#' @param permutations Integer n-by-B matrix permuting X rows.
#' @param max_kernel_evaluations Strict upper bound on symmetrized kernel terms.
#' @param keep_estimates Whether to return the observed coordinate-pair estimates.
#' @param keep_permutation Whether to return permutation sum statistics.
#' @return Exact observed and intrinsic-permutation components.
#' @keywords internal
cpp_ch4_completion_vector_u_core <- function(x, y, measure, permutations, max_kernel_evaluations, keep_estimates, keep_permutation) {
    .Call(`_HDElliptical_cpp_ch4_completion_vector_u_core`, x, y, measure, permutations, max_kernel_evaluations, keep_estimates, keep_permutation)
}

cpp_ch4ind_wilks_core <- function(x, y) {
    .Call(`_HDElliptical_cpp_ch4ind_wilks_core`, x, y)
}

cpp_ch4ind_pairwise_core <- function(residuals, keep_correlations) {
    .Call(`_HDElliptical_cpp_ch4ind_pairwise_core`, residuals, keep_correlations)
}

cpp_ch4ind_serial_panel_core <- function(residuals, nu, estimate_temporal, temporal_covariance, keep_matrices) {
    .Call(`_HDElliptical_cpp_ch4ind_serial_panel_core`, residuals, nu, estimate_temporal, temporal_covariance, keep_matrices)
}

cpp_ch4ind_rank_vector_core <- function(x, y, measure, permutations, keep_correlations, keep_permutation) {
    .Call(`_HDElliptical_cpp_ch4ind_rank_vector_core`, x, y, measure, permutations, keep_correlations, keep_permutation)
}

cpp_zhang_feng_radial_directional <- function(x, location, shape, relative_zero_tol, bootstrap_replicates) {
    .Call(`_HDElliptical_cpp_zhang_feng_radial_directional`, x, location, shape, relative_zero_tol, bootstrap_replicates)
}

cpp_ch4wn_flm_core <- function(residuals, lag, keep_lag) {
    .Call(`_HDElliptical_cpp_ch4wn_flm_core`, residuals, lag, keep_lag)
}

cpp_ch4wn_spatial_sign_core <- function(residuals, lag, keep_signs) {
    .Call(`_HDElliptical_cpp_ch4wn_spatial_sign_core`, residuals, lag, keep_signs)
}

cpp_ch4wn_rank_max_core <- function(x, lag, measure, keep_lag) {
    .Call(`_HDElliptical_cpp_ch4wn_rank_max_core`, x, lag, measure, keep_lag)
}

cpp_ch5_classical_linear_scores <- function(x, coefficients, intercept) {
    .Call(`_HDElliptical_cpp_ch5_classical_linear_scores`, x, coefficients, intercept)
}

cpp_ch5_classical_quadratic_scores <- function(x, quadratic, linear, intercept) {
    .Call(`_HDElliptical_cpp_ch5_classical_quadratic_scores`, x, quadratic, linear, intercept)
}

cpp_ch5_classical_mahalanobis_pairs <- function(x, location1, precision1, location2, precision2) {
    .Call(`_HDElliptical_cpp_ch5_classical_mahalanobis_pairs`, x, location1, precision1, location2, precision2)
}

cpp_ch5_classical_two_class_moments <- function(x, class_id) {
    .Call(`_HDElliptical_cpp_ch5_classical_two_class_moments`, x, class_id)
}

cpp_ch5_classical_fair_criterion <- function(t_squared, ordered_correlation, n1, n2) {
    .Call(`_HDElliptical_cpp_ch5_classical_fair_criterion`, t_squared, ordered_correlation, n1, n2)
}

cpp_ch5_classical_hard_threshold_covariance <- function(covariance, threshold) {
    .Call(`_HDElliptical_cpp_ch5_classical_hard_threshold_covariance`, covariance, threshold)
}

cpp_ch5_gqda_components <- function(x, location1, location2, precision1, precision2) {
    .Call(`_HDElliptical_cpp_ch5_gqda_components`, x, location1, location2, precision1, precision2)
}

cpp_c5lin_dantzig <- function(a, target, lambda, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_c5lin_dantzig`, a, target, lambda, tolerance, maximum_iterations)
}

cpp_c5lin_dsda <- function(x, response, lambda, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_c5lin_dsda`, x, response, lambda, tolerance, maximum_iterations)
}

cpp_c5qda_operator <- function(S1, S2, D, adjoint = FALSE) {
    .Call(`_HDElliptical_cpp_c5qda_operator`, S1, S2, D, adjoint)
}

cpp_c5qda_li_shao <- function(x1, x2, threshold_mean, threshold_difference, threshold_covariance, ridge) {
    .Call(`_HDElliptical_cpp_c5qda_li_shao`, x1, x2, threshold_mean, threshold_difference, threshold_covariance, ridge)
}

cpp_c5qda_jiang_matrix <- function(S1, S2, lambda, rho, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_c5qda_jiang_matrix`, S1, S2, lambda, rho, tolerance, max_iterations)
}

cpp_c5qda_jiang_vector <- function(H, gamma, lambda, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_c5qda_jiang_vector`, H, gamma, lambda, tolerance, max_iterations)
}

cpp_c5qda_dantzig_matrix <- function(S1, S2, lambda, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_c5qda_dantzig_matrix`, S1, S2, lambda, tolerance, max_iterations)
}

cpp_c5qda_dantzig_vector <- function(S, target, lambda, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_c5qda_dantzig_vector`, S, target, lambda, tolerance, max_iterations)
}

cpp_c5qda_ssqda_moments <- function(x, center, zero_tolerance) {
    .Call(`_HDElliptical_cpp_c5qda_ssqda_moments`, x, center, zero_tolerance)
}

cpp_c5qda_signed_logdet <- function(x) {
    .Call(`_HDElliptical_cpp_c5qda_signed_logdet`, x)
}

cpp_ch6cf_center_moments <- function(x, center, divisor) {
    .Call(`_HDElliptical_cpp_ch6cf_center_moments`, x, center, divisor)
}

cpp_ch6cf_cca_moments <- function(x, y, center_x, center_y, divisor) {
    .Call(`_HDElliptical_cpp_ch6cf_cca_moments`, x, y, center_x, center_y, divisor)
}

cpp_ch6cf_rts_components <- function(x, center, loadings) {
    .Call(`_HDElliptical_cpp_ch6cf_rts_components`, x, center, loadings)
}

cpp_ch6rs_radial_transform <- function(centered, weight, cutoffs, zero_tol) {
    .Call(`_HDElliptical_cpp_ch6rs_radial_transform`, centered, weight, cutoffs, zero_tol)
}

cpp_ch6spc_tpm <- function(operator_matrix, sparsity, initial, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_ch6spc_tpm`, operator_matrix, sparsity, initial, tolerance, maximum_iterations)
}

cpp_ch6spc_fantope <- function(covariance, rank, tau, rho, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_ch6spc_fantope`, covariance, rank, tau, rho, tolerance, maximum_iterations)
}

cpp_ch6spc_pmd_pca <- function(x, l1_bounds, initial, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_ch6spc_pmd_pca`, x, l1_bounds, initial, tolerance, maximum_iterations)
}

cpp_ch6spc_pmd_cca <- function(x, y, l1_x, l1_y, initial_x, initial_y, tolerance, maximum_iterations) {
    .Call(`_HDElliptical_cpp_ch6spc_pmd_cca`, x, y, l1_x, l1_y, initial_x, initial_y, tolerance, maximum_iterations)
}

cpp_ch6_sscca_primary <- function(metric_x, metric_y, cross, lambda_x, lambda_y, selection, sample_size, tolerance, max_iterations, inner_tolerance, inner_max_iterations, support_tolerance) {
    .Call(`_HDElliptical_cpp_ch6_sscca_primary`, metric_x, metric_y, cross, lambda_x, lambda_y, selection, sample_size, tolerance, max_iterations, inner_tolerance, inner_max_iterations, support_tolerance)
}

cpp_ch6_sign_whitened_pmd <- function(cross, l1_x, l1_y, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ch6_sign_whitened_pmd`, cross, l1_x, l1_y, tolerance, max_iterations)
}

cpp_ch7_chime_fit <- function(x, initial_omega, initial_mu1, initial_mu2, initial_covariance, lambda, tolerance, max_sweeps) {
    .Call(`_HDElliptical_cpp_ch7_chime_fit`, x, initial_omega, initial_mu1, initial_mu2, initial_covariance, lambda, tolerance, max_sweeps)
}

cpp_ch7_if_scores <- function(x, software_convention) {
    .Call(`_HDElliptical_cpp_ch7_if_scores`, x, software_convention)
}

cpp_ch7_if_null_scores <- function(sample_size, repetitions, software_convention) {
    .Call(`_HDElliptical_cpp_ch7_if_null_scores`, sample_size, repetitions, software_convention)
}

cpp_ch7_if_deterministic_kmeans <- function(embedding, clusters, tolerance, max_iterations) {
    .Call(`_HDElliptical_cpp_ch7_if_deterministic_kmeans`, embedding, clusters, tolerance, max_iterations)
}

cpp_ch7cs_lloyd_core <- function(x, initial_centers, empty_action, solver_tolerance, maximum_iterations, keep_distances) {
    .Call(`_HDElliptical_cpp_ch7cs_lloyd_core`, x, initial_centers, empty_action, solver_tolerance, maximum_iterations, keep_distances)
}

cpp_ch7cs_gmm_core <- function(x, means, covariances, proportions, ridge, solver_tolerance, monotone_tolerance, rank_tolerance, maximum_iterations, keep_responsibilities) {
    .Call(`_HDElliptical_cpp_ch7cs_gmm_core`, x, means, covariances, proportions, ridge, solver_tolerance, monotone_tolerance, rank_tolerance, maximum_iterations, keep_responsibilities)
}

cpp_ch7cs_sparse_kmeans_core <- function(x, initial_centers, l1_bound, empty_action, weight_tolerance, weight_maximum_iterations, solver_tolerance, maximum_iterations, keep_distances) {
    .Call(`_HDElliptical_cpp_ch7cs_sparse_kmeans_core`, x, initial_centers, l1_bound, empty_action, weight_tolerance, weight_maximum_iterations, solver_tolerance, maximum_iterations, keep_distances)
}

cpp_ch7cs_sparse_kmedian_core <- function(x, initial_centers, l1_bound, empty_action, score_tolerance, weight_tolerance, weight_maximum_iterations, solver_tolerance, maximum_iterations, keep_distances) {
    .Call(`_HDElliptical_cpp_ch7cs_sparse_kmedian_core`, x, initial_centers, l1_bound, empty_action, score_tolerance, weight_tolerance, weight_maximum_iterations, solver_tolerance, maximum_iterations, keep_distances)
}

cpp_ch7_semc_delta <- function(x, centers, precision) {
    .Call(`_HDElliptical_cpp_ch7_semc_delta`, x, centers, precision)
}

cpp_ch7_semc_softmax <- function(log_scores) {
    .Call(`_HDElliptical_cpp_ch7_semc_softmax`, log_scores)
}

cpp_ch7_semc_weighted_sign_scatter <- function(residuals, weights, radial_floor) {
    .Call(`_HDElliptical_cpp_ch7_semc_weighted_sign_scatter`, residuals, weights, radial_floor)
}

cpp_ch7_semc_weighted_tyler <- function(residuals, weights, initial_shape, ridge, radial_floor, tolerance, max_iterations, spd_tol) {
    .Call(`_HDElliptical_cpp_ch7_semc_weighted_tyler`, residuals, weights, initial_shape, ridge, radial_floor, tolerance, max_iterations, spd_tol)
}

cpp_ch7_semc_offdiag_glasso <- function(scatter, lambda, tolerance, max_iterations, initial_step, max_backtracking, spd_tol, majorization_tolerance) {
    .Call(`_HDElliptical_cpp_ch7_semc_offdiag_glasso`, scatter, lambda, tolerance, max_iterations, initial_step, max_backtracking, spd_tol, majorization_tolerance)
}

cpp_ch7_semc_weighted_kde <- function(evaluation_grid, observations, weights, bandwidth) {
    .Call(`_HDElliptical_cpp_ch7_semc_weighted_kde`, evaluation_grid, observations, weights, bandwidth)
}

#' Euclidean assignment kernel for Chapter 7 spatial clustering
#'
#' @param x Finite observation-by-variable matrix.
#' @param centers Finite cluster-by-variable center matrix.
#' @param active Zero-based active coordinate indices.
#' @param keep_matrix Whether to retain every observation-center distance.
#' @return Internal deterministic assignment and distance diagnostics.
#' @keywords internal
cpp_ch7sc_assign_euclidean <- function(x, centers, active, keep_matrix) {
    .Call(`_HDElliptical_cpp_ch7sc_assign_euclidean`, x, centers, active, keep_matrix)
}

#' SSCM and exact inverse for Chapter 7 spatial clustering
#'
#' @param x Finite observation-by-variable matrix.
#' @param centers Finite cluster-by-variable center matrix.
#' @param labels One-based cluster labels.
#' @param lambda Strictly positive ridge in the stated SSCM definition.
#' @param zero_tol Non-negative zero-residual tolerance.
#' @param keep_signs Whether to retain the residual spatial signs.
#' @return Internal SSCM, inverse, and finite-sample certificates.
#' @keywords internal
cpp_ch7sc_sscm_metric <- function(x, centers, labels, lambda, zero_tol, keep_signs) {
    .Call(`_HDElliptical_cpp_ch7sc_sscm_metric`, x, centers, labels, lambda, zero_tol, keep_signs)
}

#' SSCM metric assignment kernel for Chapter 7
#'
#' @param x Finite observation-by-variable matrix.
#' @param centers Finite cluster-by-variable center matrix.
#' @param inverse_metric Finite symmetric positive-definite inverse SSCM.
#' @param keep_matrix Whether to retain every squared metric distance.
#' @return Internal deterministic assignment and distance diagnostics.
#' @keywords internal
cpp_ch7sc_assign_metric <- function(x, centers, inverse_metric, keep_matrix) {
    .Call(`_HDElliptical_cpp_ch7sc_assign_metric`, x, centers, inverse_metric, keep_matrix)
}

#' Across-center feature scores for Sparse--SM
#'
#' @param centers Finite cluster-by-variable center matrix.
#' @return Internal center average and hard-screening scores.
#' @keywords internal
cpp_ch7sc_feature_scores <- function(centers) {
    .Call(`_HDElliptical_cpp_ch7sc_feature_scores`, centers)
}

#' Active-subspace geometry for Sparse--SM selectors
#'
#' @param x Finite observation-by-variable matrix.
#' @param centers Finite cluster-by-variable center matrix.
#' @param labels One-based cluster labels.
#' @param overall Finite vector in the same coordinate convention as centers.
#' @param active Zero-based active coordinate indices.
#' @return Internal between- and within-spatial-median geometry.
#' @keywords internal
cpp_ch7sc_geometry <- function(x, centers, labels, overall, active) {
    .Call(`_HDElliptical_cpp_ch7sc_geometry`, x, centers, labels, overall, active)
}

